### ISSUE TITLE
友情链接 | isekiのNote

### ISSUE THREAD

**Issue by iseki0** [cpdyj/blog#11]
https://blog.iseki.space/link/ 

 友情链接

**Comment by EpLiar** [comment]
Hi Iseki

![I always like Iseki](https://epliar.com/img/iseki.png)

**Comment by iseki0** [comment]
> @EpLiar
> Hi Iseki
> 
> ![I always like Iseki](https://epliar.com/img/iseki.png)

是聚聚，聚聚tql，聚聚不介意的话友链下？（把头像和一句话给我（x
