### ISSUE TITLE
Gradle 里执行 Jar 的几种办法 | isekiのNote

### ISSUE THREAD

**Issue by iseki0** [cpdyj/blog#22]
https://blog.iseki.space/2020/04/11/gradle-execute-jar/ 

 Gradle 里执行 Jar 的几种办法

**Comment by hurui200320** [comment]
从Github状态而来（Kotlin真香），之前写Kotlin一直在用Maven，后来使用gRPC重构，maven配置起来真的太反人类了，遂被逼就换到了Gradle，一开始不太适应（现在也不适应），但是就感觉好像比maven好用了那么亿点点XD

**Comment by iseki0** [comment]
呐，主要是maven的XML一看到就头大
